packages:
  - name: ask
    environment:
      # DO will inject this from your deployment command
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL}" 
    functions:
      - name: submit
        runtime: "nodejs:default"
        web: true # This makes it publicly accessible via HTTP
